# Generated by Django 4.2.7 on 2023-11-18 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_movie_description_movie_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie", name="name", field=models.CharField(max_length=200),
        ),
    ]
