# Generated by Django 4.2.7 on 2023-11-25 00:28

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("movies", "0003_alter_movie_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie", old_name="updated", new_name="updated_at",
        ),
        migrations.AddField(
            model_name="movie",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2023, 11, 25, 0, 27, 51, 587793),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="movie",
            name="posted_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="rating",
            field=models.PositiveIntegerField(
                default=10,
                validators=[
                    django.core.validators.MaxValueValidator(10),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="movie",
            name="year",
            field=models.PositiveIntegerField(default=1975),
            preserve_default=False,
        ),
    ]
